export const gameItems = [
  {
    id: "weapon_basic_rapier",
    name: "Базовая рапира",
    description: "Простое оружие для любителей фехтования",
    price: 1000,
    stats: "",
    canBeSold: true,
    damagePercentBonus: 0.1,
    accuracyBonus: 0.2,
    critChanceBonus: -0.15,
  },
  {
    id: "weapon_basic_broadsword",
    name: "Базовый палаш",
    description: "Простое оружие для любителей рубить наотмашь",
    price: 1000,
    stats: "Оружие для кровавых убийств",
    canBeSold: true,
    damagePercentBonus: 0.2,
    accuracyBonus: 0.05,
    critChanceBonus: 0.1,
  },
  {
    id: "weapon_basic_longsword",
    name: "Базовый длинный меч",
    description: "Простое оружие для тех кто не определился",
    price: 1000,
    stats: "Оружие для отсечения голов",
    canBeSold: true,
    damagePercentBonus: 0.2,
    accuracyBonus: 0.1,
    critChanceBonus: 0.05,
  },
  {
    id: "weapon_basic_greatsword",
    name: "Базовый огромный меч",
    description: "Простое оружие для настоящих рубил",
    price: 1000,
    stats: "Рубить это призвание",
    canBeSold: true,
    damagePercentBonus: 0.3,
    accuracyBonus: -0.3,
    critChanceBonus: 0.2,
  },
  {
    id: "armor_basic_light",
    name: "Базовая лёгкая броня",
    description: "Лёгкая броня для минимальной защиты.",
    price: 1000,
    stats: "Любишь подвигаться?",
    canBeSold: true,
    defensePercentBonus: 0.1,
    accuracyBonus: 0.1,
  },
  {
    id: "armor_basic_medium",
    name: "Базовая средняя броня",
    description: "Средняя броня для неплохой защиты.",
    price: 1000,
    stats: "Для опытных бойцов",
    canBeSold: true,
    defensePercentBonus: 0.15,
    accuracyBonus: 0.05,
  },
  {
    id: "armor_basic_heavy",
    name: "Базовая тяжелая броня",
    description: "Тяжелая неудобная броня для хорошей защиты.",
    price: 1000,
    stats: "Для настоящих безумцев",
    canBeSold: true,
    defensePercentBonus: 0.25,
    accuracyBonus: -0.1,
  },
  {
    id: "weapon_epic_rapier",
    name: "Базовая рапира",
    description: "Простое оружие для любителей фехтования",
    stats: "Эпическая рапира пронзившая множество воинов",
    canBeSold: false,
    damagePercentBonus: 0.2,
    accuracyBonus: 0.3,
    critChanceBonus: -0.25,
  },
  {
    id: "weapon_epic_broadsword",
    name: "Эпический палаш",
    description: "Простое оружие для любителей рубить наотмашь",
    stats: "Эпическое оружие закаленное сотнями битв",
    canBeSold: false,
    damagePercentBonus: 0.3,
    accuracyBonus: 0.15,
    critChanceBonus: 0.2,
  },
  {
    id: "weapon_epic_longsword",
    name: "Эпический длинный меч",
    description: "Простое оружие для тех кто не определился",
    stats: "Эпическое оружие бесславного рыцаря",
    canBeSold: false,
    damagePercentBonus: 0.3,
    accuracyBonus: 0.2,
    critChanceBonus: 0.15,
  },
  {
    id: "weapon_epic_greatsword",
    name: "Эпический огромный меч",
    description: "Простое оружие для настоящих рубил",
    stats: "Эпический огромный меч безимянного воина",
    canBeSold: false,
    damagePercentBonus: 0.4,
    accuracyBonus: -0.3,
    critChanceBonus: 0.3,
  },
  {
    id: "armor_epic_light",
    name: "Эпическая лёгкая броня",
    description: "Лёгкая броня для минимальной защиты.",
    stats: "Пронизанная кровью эпическая броня",
    canBeSold: false,
    defensePercentBonus: 0.2,
    accuracyBonus: 0.2,
  },
  {
    id: "armor_epic_medium",
    name: "Эпическая средняя броня",
    description: "Средняя броня для неплохой защиты.",
    stats: "Эпическая средняя броня опытного воина",
    canBeSold: false,
    defensePercentBonus: 0.25,
    accuracyBonus: 0.15,
  },
  {
    id: "armor_epic_heavy",
    name: "Эпическая тяжелая броня",
    description: "Тяжелая неудобная броня для хорошей защиты.",
    stats: "Мощная эпическая броня из прочных сплавов",
    canBeSold: false,
    defensePercentBonus: 0.35,
    accuracyBonus: -0.2,
  },
  {
    id: "weapon_mythic_broadsword",
    name: "Эпический палаш",
    description: "Простое оружие для любителей рубить наотмашь",
    stats: "",
    canBeSold: false,
    damagePercentBonus: 0.3,
    accuracyBonus: 0.15,
    critChanceBonus: 0.2,
  },
  {
    id: "weapon_mythic_longsword",
    name: "Эпический длинный меч",
    description: "Простое оружие для тех кто не определился",
    stats: "",
    canBeSold: false,
    damagePercentBonus: 0.3,
    accuracyBonus: 0.2,
    critChanceBonus: 0.15,
  },
  {
    id: "weapon_mythic_greatsword",
    name: "Эпический огромный меч",
    description: "Простое оружие для настоящих рубил",
    stats: "",
    canBeSold: false,
    damagePercentBonus: 0.4,
    accuracyBonus: -0.3,
    critChanceBonus: 0.3,
  },
  {
    id: "armor_mythic_light",
    name: "Эпическая лёгкая броня",
    description: "Лёгкая броня для минимальной защиты.",
    stats: "Защита: 10% от основного аттрибута",
    canBeSold: false,
    defensePercentBonus: 0.2,
    accuracyBonus: 0.2,
  },
  {
    id: "armor_mythic_medium",
    name: "Эпическая средняя броня",
    description: "Средняя броня для неплохой защиты.",
    stats: "Защита: 20% от основного аттрибута",
    canBeSold: false,
    defensePercentBonus: 0.25,
    accuracyBonus: 0.15,
  },
  {
    id: "armor_mythic_heavy",
    name: "Эпическая тяжелая броня",
    description: "Тяжелая неудобная броня для хорошей защиты.",
    stats: "Защита: 30% от основного аттрибута",
    canBeSold: false,
    defensePercentBonus: 0.35,
    accuracyBonus: -0.2,
  },
  {
    id: "weapon_legendary_broadsword",
    name: "Эпический палаш",
    description: "Простое оружие для любителей рубить наотмашь",
    stats: "",
    canBeSold: false,
    damagePercentBonus: 0.3,
    accuracyBonus: 0.15,
    critChanceBonus: 0.2,
  },
  {
    id: "weapon_legendary_longsword",
    name: "Эпический длинный меч",
    description: "Простое оружие для тех кто не определился",
    stats: "",
    canBeSold: false,
    damagePercentBonus: 0.3,
    accuracyBonus: 0.2,
    critChanceBonus: 0.15,
  },
  {
    id: "weapon_legendary_greatsword",
    name: "Эпический огромный меч",
    description: "Простое оружие для настоящих рубил",
    stats: "",
    canBeSold: false,
    damagePercentBonus: 0.4,
    accuracyBonus: -0.3,
    critChanceBonus: 0.3,
  },
  {
    id: "armor_legendary_light",
    name: "Эпическая лёгкая броня",
    description: "Лёгкая броня для минимальной защиты.",
    stats: "Защита: 10% от основного аттрибута",
    canBeSold: false,
    defensePercentBonus: 0.2,
    accuracyBonus: 0.2,
  },
  {
    id: "armor_legendary_medium",
    name: "Эпическая средняя броня",
    description: "Средняя броня для неплохой защиты.",
    stats: "Защита: 20% от основного аттрибута",
    canBeSold: false,
    defensePercentBonus: 0.25,
    accuracyBonus: 0.15,
  },
  {
    id: "armor_legendary_heavy",
    name: "Эпическая тяжелая броня",
    description: "Тяжелая неудобная броня для хорошей защиты.",
    stats: "Защита: 30% от основного аттрибута",
    canBeSold: false,
    defensePercentBonus: 0.35,
    accuracyBonus: -0.2,
  },
  {
    id: "potion_damage",
    name: "Зелье урона",
    description: "Зелье, повышающее урон на 10% на 5 дуэлей.",
    price: 500,
    stats: "Урон +10% (5 дуэлей)",
    canBeSold: true,
  },
  {
    id: "potion_defense",
    name: "Зелье защиты",
    description: "Зелье, повышающее защиту на 10% на 5 дуэлей.",
    price: 500,
    stats: "Защита +10% (5 дуэлей)",
    canBeSold: true,
  },
  {
    id: "scroll_weapon",
    name: "Заточка оружия",
    description: "Свиток для улучшения оружия. Риск разрушения!",
    price: 700,
    stats: "Шанс улучшить оружие (+1)",
    canBeSold: true,
  },
  {
    id: "scroll_armor",
    name: "Усиление брони",
    description: "Свиток для усиления брони. Риск разрушения!",
    price: 700,
    stats: "Шанс усилить броню (+1)",
    canBeSold: true,
  },
  /*
  {
    id: "weapon_epic",
    name: "Эпическое оружие",
    description: "Оружие, созданное древними кузнецами.",
    stats: "Урон: +50%, Точность: +20%, Крит: +10%",
    canBeSold: false,
    damagePercentBonus: 0.5,
    accuracyBonus: 0.2,
    critChanceBonus: 0.1,
  },
  {
    id: "armor_epic",
    name: "Эпическая броня",
    description: "Доспехи из мифрила с рунической защитой.",
    stats: "Защита: +30%",
    canBeSold: false,
    defensePercentBonus: 0.3,
  },
  {
    id: "weapon_legendary",
    name: "Легендарное оружие",
    description: "Артефакт, о котором слагают легенды.",
    stats: "Урон: +100%, Точность: +50%, Крит: +20%",
    canBeSold: false,
    damagePercentBonus: 1.0,
    accuracyBonus: 0.5,
    critChanceBonus: 0.2,
  },
  */
];
