export const gameItems = [
  {
    id: "weapon_basic",
    name: "Базовое оружие",
    description: "Простое оружие для начинающих бойцов.",
    price: 1000,
    stats: "Урон: +30% от основного аттрибута",
    canBeSold: true,
    damagePercentBonus: 0.3,
    accuracyBonus: 0,
    critChanceBonus: 0,
  },
  {
    id: "armor_basic",
    name: "Базовая броня",
    description: "Лёгкая броня для минимальной защиты.",
    price: 1000,
    stats: "Защита: 10% от основного аттрибута",
    canBeSold: true,
    defensePercentBonus: 0.1,
  },
  {
    id: "potion_damage",
    name: "Зелье урона",
    description: "Зелье, повышающее урон на 10% на 5 дуэлей.",
    price: 500,
    stats: "Урон +10% (5 дуэлей)",
    canBeSold: true,
  },
  {
    id: "potion_defense",
    name: "Зелье защиты",
    description: "Зелье, повышающее защиту на 10% на 5 дуэлей.",
    price: 500,
    stats: "Защита +10% (5 дуэлей)",
    canBeSold: true,
  },
  {
    id: "scroll_weapon",
    name: "Заточка оружия",
    description: "Свиток для улучшения оружия. Риск разрушения!",
    price: 700,
    stats: "Шанс улучшить оружие (+1)",
    canBeSold: true,
  },
  {
    id: "scroll_armor",
    name: "Усиление брони",
    description: "Свиток для усиления брони. Риск разрушения!",
    price: 700,
    stats: "Шанс усилить броню (+1)",
    canBeSold: true,
  },
  {
    id: "weapon_epic",
    name: "Эпическое оружие",
    description: "Оружие, созданное древними кузнецами.",
    stats: "Урон: +50%, Точность: +20%, Крит: +10%",
    canBeSold: false,
    damagePercentBonus: 0.5,
    accuracyBonus: 0.2,
    critChanceBonus: 0.1,
  },
  {
    id: "armor_epic",
    name: "Эпическая броня",
    description: "Доспехи из мифрила с рунической защитой.",
    stats: "Защита: +30%",
    canBeSold: false,
    defensePercentBonus: 0.3,
  },
  {
    id: "weapon_legendary",
    name: "Легендарное оружие",
    description: "Артефакт, о котором слагают легенды.",
    stats: "Урон: +100%, Точность: +50%, Крит: +20%",
    canBeSold: false,
    damagePercentBonus: 1.0,
    accuracyBonus: 0.5,
    critChanceBonus: 0.2,
  },
];
